export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS'
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS'
/* SIGN IN */
export const SIGN_IN = 'socket/SIGN_IN'
/* SIGN OUT */
export const SIGN_OUT = 'SIGN_OUT'
export const SPINNER = 'SPINNER'
/* SNACK */
export const SNACK = 'SNACK'

export const SESSION_STATE = 'SESSION_STATE'
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET'

// placeholder action
export const ACTION = 'ACTION'
//

export const LOAD_MORE_GUIDES = 'socket/LOAD_MORE_GUIDES'

export const GET_GUIDES = 'LOAD_MORE_GUIDES'

export const RESET_GUIDES = 'RESET_GUIDES'
// DASHBOARD

export const GET_DISTRIBUTION_CENTERS = 'socket/GET_DISTRIBUTION_CENTERS'
export const SET_DISTRIBUTION_CENTERS = 'SET_DISTRIBUTION_CENTERS'
export const GET_BREWERIES_WH = 'socket/GET_BREWERIES_WH'
export const SET_BREWERIES_WH = 'SET_BREWERIES_WH'
export const RESET_BREWERIES_WH = 'RESET_BREWERIES_WH'
export const SET_BREWERIES_PRODUCTS = 'SET_BREWERIES_PRODUCTS'

// PRODUCTS PRESET
export const PRODUCTS_PRESETS_SET = 'PRODUCTS_PRESETS_SET'

// PRODUCTS LIST
export const SHOW_MORE_PRODUCTS = 'SHOW_MORE_PRODUCTS'
export const SET_PRODUCTS_COLUMNS = 'SET_PRODUCTS_COLUMNS'
export const LOAD_MORE_PRODUCTS = 'socket/LOAD_MORE_PRODUCTS'
export const DELETE_PRODUCTS = 'socket/DELETE_PRODUCTS'
export const UPDATE_PRODUCT = 'socket/UPDATE_PRODUCT'
export const UPDATE_PRODUCTS_LIST = 'UPDATE_PRODUCTS_LIST'
export const FORCE_RENDER = 'FORCE_RENDER'
export const ADD_PRODUCT = 'socket/ADD_PRODUCT'
export const GET_PRODUCT_MODEL = 'socket/GET_PRODUCT_MODEL'
export const GET_WHOLESALERS = 'socket/GET_WHOLESALERS'
export const SET_WHOLESALERS = 'SET_WHOLESALERS'

// PRODUCTS LIST VIEW SETTINGS
export const APPLY_PRODUCTS_LIST_SETTINGS = 'APPLY_PRODUCTS_LIST_SETTINGS'

export const GET_FILES_LIST = 'socket/GET_FILES_LIST'
export const FILES_LIST = 'GET_FILES_LIST'

// PRODUCT DETAILS
export const SET_PRODUCT_DETAILS_COLUMNS = 'SET_PRODUCT_DETAILS_COLUMNS'
export const GET_THIS_PRODUCT = 'socket/GET_THIS_PRODUCT'
export const SHOW_THIS_PRODUCT = 'SHOW_THIS_PRODUCT'
export const GET_ORDERS_FOR_PRODUCT = 'socket/GET_ORDERS_FOR_PRODUCT'
export const SHOW_ORDERS_FOR_PRODUCT = 'SHOW_ORDERS_FOR_PRODUCT'
// BREWERIES
export const BREWERIES_LOAD = 'socket/BREWERIES_LOAD'
export const BREWERIES_SHOW = 'BREWERIES_SHOW'
export const BREWERIES_RESET = 'BREWERIES_RESET'

// SPLITS
export const SPLITS_GET_MODEL = 'socket/SPLITS_GET_MODEL'
export const SPLITS_LOAD_MORE = 'socket/SPLITS_LOAD_MORE'
export const SPLITS_FORCE_RENDER = 'SPLITS_FORCE_RENDER'
export const SPLITS_SET_COLUMNS = 'SPLITS_SET_COLUMNS'
export const SPLITS_APPLY_SETTINGS = 'SPLITS_APPLY_SETTINGS'
export const SPLITS_SHOW_MORE = 'SPLITS_SHOW_MORE'

// SPLITS PRESETS
export const SPLITS_PRESETS_GET = 'socket/SPLITS_PRESETS_GET'
export const SPLITS_PRESETS_SET = 'SPLITS_PRESETS_SET'
export const SPLITS_PRESETS_SAVE = 'socket/SPLITS_PRESETS_SAVE'
export const SPLITS_PRESETS_REMOVE = 'socket/SPLITS_PRESETS_REMOVE'

// LOCAL USERS
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const CHANGE_USER = 'CHANGE_USER'

// WHOLESALERS
export const WHOLESALERS_LOAD = 'socket/WHOLESALERS_LOAD'
export const WHOLESALERS_SHOW = 'WHOLESALERS_SHOW'

// ADD PRODUCT TO ORDER
export const ADD_TO_ORDER = 'socket/ADD_TO_ORDER'

// ORDERS
export const GET_ORDER_MODEL = 'socket/GET_ORDER_MODEL'
export const SET_ORDERS_COLUMNS = 'SET_ORDERS_COLUMNS'
export const LOAD_MORE_ORDERS = 'socket/LOAD_MORE_ORDERS'
export const SHOW_MORE_ORDERS = 'SHOW_MORE_ORDERS'
export const REQUIRE_ORDER_UPDATE = 'REQUIRE_ORDER_UPDATE'
export const ORDER_SET_NAME = 'ORDER_SET_NAME'

// ORDERS PRESET
export const ORDERS_PRESETS_SET = 'ORDERS_PRESETS_SET'

// ORDERS VIEW SETTINGS
export const APPLY_ORDERS_LIST_SETTINGS = 'APPLY_ORDERS_LIST_SETTINGS'

// ORDER DETAILS
export const UPDATE_ORDER = 'socket/UPDATE_ORDER'
export const GET_THIS_ORDER = 'socket/GET_THIS_ORDER'
export const SHOW_ORDER = 'SHOW_ORDER'

// GENERAL PRESETS
export const PRESETS_GET = 'socket/PRESETS_GET'
export const PRESETS_SAVE = 'socket/PRESETS_SAVE'
export const PRESETS_REMOVE = 'socket/PRESETS_REMOVE'

// ALLOCATIONS
export const SHOW_MORE_ALLOCATIONS = 'SHOW_MORE_ALLOCATIONS'
export const ALLOCATIONS_PRESETS_SET = 'ALLOCATIONS_PRESETS_SET'

// TRANSFERS
export const TRANSFERS_LOAD = 'socket/TRANSFERS_LOAD'
export const TRANSFERS_SHOW = 'TRANSFERS_SHOW'
